# Generated by Django 4.2.4 on 2024-01-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temperatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='tempModeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempMode', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='UssModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uss', models.CharField(max_length=4)),
            ],
        ),
    ]
