# Generated by Django 4.2.4 on 2024-01-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_iot', models.CharField(max_length=7)),
                ('temp_mode_iot', models.CharField(max_length=7)),
                ('uss_iot', models.CharField(max_length=7)),
            ],
        ),
    ]
