# Generated by Django 4.2.4 on 2024-01-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_iotmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temperatureModel',
        ),
        migrations.DeleteModel(
            name='tempModeModel',
        ),
        migrations.DeleteModel(
            name='UssModel',
        ),
    ]
